services:
  spring-app:
    container_name: spring-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wktechnology
      MYSQL_ROOT_PASSWORD: root