services:
  spring-app:
    container_name: wk-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: wk-database
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wktechnology
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5